import "@myleaper/ui/globals.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Provider } from "@/components/providers"
import { ThemeProvider } from "@/components/providers/theme-provider"

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Provider>
        <body className={`${inter.className} antialiased`}>
          <ThemeProvider>{children}</ThemeProvider>
        </body>
      </Provider>
    </html>
  )
}
