import "@app/ui/globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Provider } from "@/components/providers"
import { ReactScan } from "@/components/ui/react-scan"

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en" className="scroll-smooth" suppressHydrationWarning>
      <ReactScan />
      <body className={`${inter.className} antialiased`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
