import { FontIcons } from "@/features/bussiness/components/shared/font-icons"
import type { FontOption } from "@/features/bussiness/types"

// Modern Fonts
export const MODERN_FONTS = [
  {
    id: "inter",
    family: "Inter",
    headingWeight: 600,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: FontIcons.inter,
  },
  {
    id: "lato",
    family: "Lato",
    headingWeight: 700,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: FontIcons.lato,
  },
  {
    id: "montserrat",
    family: "Montserrat",
    headingWeight: 600,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: FontIcons.montserrat,
  },
  {
    id: "space-grotesk",
    family: "Space Grotesk",
    headingWeight: 600,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: FontIcons.spaceGrotesk,
  },
  {
    id: "poppins",
    family: "Poppins",
    headingWeight: 600,
    buttonWeight: 400,
    bodyWeight: 400,
    Icon: FontIcons.poppins,
  },
  {
    id: "raleway",
    family: "Raleway",
    headingWeight: 600,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: FontIcons.raleway,
  },
  {
    id: "syne",
    family: "Syne",
    headingWeight: 600,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: FontIcons.syne,
  },
  {
    id: "saira",
    family: "Saira",
    headingWeight: 600,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: FontIcons.saira,
  },
  {
    id: "ibm-plex-mono",
    family: "IBM Plex Mono",
    headingWeight: 600,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: FontIcons.plexmono,
  },
  {
    id: "roboto",
    family: "Roboto",
    headingWeight: 700,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: FontIcons.roboto,
  },
  {
    id: "nunito",
    family: "Nunito",
    headingWeight: 700,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: FontIcons.nunito,
  },
] as const satisfies FontOption[]

// Classic Fonts
export const CLASSIC_FONTS = [
  {
    id: "roboto-slab",
    family: "Roboto Slab",
    headingWeight: 500,
    buttonWeight: 400,
    bodyWeight: 400,
    Icon: FontIcons.robotoSans,
  },
  {
    id: "lora",
    family: "Lora",
    headingWeight: 700,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: FontIcons.lora,
  },
  {
    id: "merriweather",
    family: "Merriweather",
    headingWeight: 700,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: FontIcons.meriWeather,
  },
  {
    id: "gfs-didot",
    family: "GFS Didot",
    headingWeight: 400,
    buttonWeight: 400,
    bodyWeight: 400,
    Icon: FontIcons.didot,
  },
  {
    id: "ibm-plex-serif",
    family: "IBM Plex Serif",
    headingWeight: 600,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: FontIcons.plexSerif,
  },
  {
    id: "fraunces",
    family: "Fraunces",
    headingWeight: 700,
    buttonWeight: 600,
    bodyWeight: 400,
    Icon: FontIcons.fraunces,
  },
  {
    id: "inria-serif",
    family: "Inria Serif",
    headingWeight: 700,
    buttonWeight: 700,
    bodyWeight: 400,
    Icon: FontIcons.inira,
  },
  {
    id: "noto-serif",
    family: "Noto Serif",
    headingWeight: 700,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: FontIcons.notoSerif,
  },
  {
    id: "times-new-roman",
    family: "Times New Roman",
    headingWeight: 700,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: FontIcons.newRoman,
  },
] as const satisfies FontOption[]

// Fancy Fonts
export const FANCY_FONTS = [
  {
    id: "sour-gummy",
    family: "Sour Gummy",
    headingWeight: 400,
    buttonWeight: 400,
    bodyWeight: 400,
    Icon: FontIcons.sourGummy,
  },
  {
    id: "delius",
    family: "Delius",
    headingWeight: 400,
    buttonWeight: 400,
    bodyWeight: 400,
    Icon: FontIcons.delius,
  },
  {
    id: "indie-flower",
    family: "Indie Flower",
    headingWeight: 400,
    buttonWeight: 400,
    bodyWeight: 400,
    Icon: FontIcons.indieFlower,
  },
  {
    id: "satisfy",
    family: "Satisfy",
    headingWeight: 400,
    buttonWeight: 400,
    bodyWeight: 400,
    Icon: FontIcons.satisfy,
  },
  {
    id: "handlee",
    family: "Handlee",
    headingWeight: 400,
    buttonWeight: 400,
    bodyWeight: 400,
    Icon: FontIcons.handlee,
  },
] as const satisfies FontOption[]
