import { BussinessIcons } from "@/features/bussiness/components/shared/bussiness-icons"
import type { FontOption } from "@/features/bussiness/types"

// Modern Fonts
export const MODERN_FONTS: FontOption[] = [
  {
    id: "inter",
    family: "Inter",
    headingWeight: 600,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: BussinessIcons.inter,
  },
  {
    id: "lato",
    family: "Lato",
    headingWeight: 700,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: BussinessIcons.lato,
  },
  {
    id: "montserrat",
    family: "Montserrat",
    headingWeight: 600,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: BussinessIcons.montserrat,
  },
  {
    id: "space-grotesk",
    family: "Space Grotesk",
    headingWeight: 600,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: BussinessIcons.spaceGrotesk,
  },
  {
    id: "poppins",
    family: "Poppins",
    headingWeight: 600,
    buttonWeight: 400,
    bodyWeight: 400,
    Icon: BussinessIcons.poppins,
  },
  {
    id: "raleway",
    family: "Raleway",
    headingWeight: 600,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: BussinessIcons.raleway,
  },
  {
    id: "syne",
    family: "Syne",
    headingWeight: 600,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: BussinessIcons.syne,
  },
  {
    id: "saira",
    family: "Saira",
    headingWeight: 600,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: BussinessIcons.saira,
  },
  {
    id: "ibm-plex-mono",
    family: "IBM Plex Mono",
    headingWeight: 600,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: BussinessIcons.plexmono,
  },
  {
    id: "roboto",
    family: "Roboto",
    headingWeight: 700,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: BussinessIcons.roboto,
  },
  {
    id: "nunito",
    family: "Nunito",
    headingWeight: 700,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: BussinessIcons.nunito,
  },
]

// Classic Fonts
export const CLASSIC_FONTS: FontOption[] = [
  {
    id: "roboto-slab",
    family: "Roboto Slab",
    headingWeight: 700,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: BussinessIcons.robotoSans,
  },
  {
    id: "lora",
    family: "Lora",
    headingWeight: 700,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: BussinessIcons.lora,
  },
  {
    id: "merriweather",
    family: "Merriweather",
    headingWeight: 700,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: BussinessIcons.meriWeather,
  },
  {
    id: "gfs-didot",
    family: "GFS Didot",
    headingWeight: 400,
    buttonWeight: 400,
    bodyWeight: 400,
    Icon: BussinessIcons.didot,
  },
  {
    id: "ibm-plex-serif",
    family: "IBM Plex Serif",
    headingWeight: 600,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: BussinessIcons.plexSerif,
  },
  {
    id: "fraunces",
    family: "Fraunces",
    headingWeight: 700,
    buttonWeight: 600,
    bodyWeight: 400,
    Icon: BussinessIcons.fraunces,
  },
  {
    id: "inria-serif",
    family: "Inria Serif",
    headingWeight: 700,
    buttonWeight: 700,
    bodyWeight: 400,
    Icon: BussinessIcons.inira,
  },
  {
    id: "noto-serif",
    family: "Noto Serif",
    headingWeight: 700,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: BussinessIcons.notoSerif,
  },
  {
    id: "times-new-roman",
    family: "Times New Roman",
    headingWeight: 700,
    buttonWeight: 500,
    bodyWeight: 400,
    Icon: BussinessIcons.newRoman,
  },
]

// Fancy Fonts
export const FANCY_FONTS: FontOption[] = [
  {
    id: "sour-gummy",
    family: "Sour Gummy",
    headingWeight: 400,
    buttonWeight: 400,
    bodyWeight: 400,
    Icon: BussinessIcons.sourGummy,
  },
  {
    id: "delius",
    family: "Delius",
    headingWeight: 400,
    buttonWeight: 400,
    bodyWeight: 400,
    Icon: BussinessIcons.delius,
  },
  {
    id: "indie-flower",
    family: "Indie Flower",
    headingWeight: 400,
    buttonWeight: 400,
    bodyWeight: 400,
    Icon: BussinessIcons.indieFlower,
  },
  {
    id: "satisfy",
    family: "Satisfy",
    headingWeight: 400,
    buttonWeight: 400,
    bodyWeight: 400,
    Icon: BussinessIcons.satisfy,
  },
  {
    id: "handlee",
    family: "Handlee",
    headingWeight: 400,
    buttonWeight: 400,
    bodyWeight: 400,
    Icon: BussinessIcons.handlee,
  },
]
